# Site settings
title: 'BenBot'
email: 'ben@tilde.team'
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bot.benharr.is" # the base hostname & protocol for your site
destination: public_html

twitter_username: nebsirrah
github_username: benharri
telegram_username: bharris

# Build settings
markdown: kramdown

