# Site settings
title: 'bots by ben'
email: 'mail@benharr.is'
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bots.benharr.is" # the base hostname & protocol for your site
destination: public_html

twitter_username: bharrismac
github_username: benharri

# Build settings
markdown: kramdown
